apps/first_app/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name="register"),
    url(r'^login$', views.login, name="login"),
    url(r'^main$', views.main, name='main'),
    url(r'^user/(?P<user_id>[^/]+)(?:/)*$', views.user, name="user"),
    url(r'^addfriend/(?P<user_id>[^/]+)(?:/)*$', views.newfriend, name="addfriend"),
	url(r'^deletefriend/(?P<user_id>[^/]+)(?:/)*$', views.byefriend, name="deletefriend"),
    url(r'^logout$', views.logout, name='logout'),
]

final_belt/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.first_app.urls', namespace='login')),
    url(r'^main', include('apps.first_app.urls', namespace='main')),
]

apps/first_app/models.py
from __future__ import unicode_literals
from django.db import models
import re
import bcrypt

class UserManager(models.Manager):
    def name_invalid(self, first_name):
        if not len(first_name) < 2 and re.search(r'^[a-zA-Z]+$', first_name):
            return False
        else:
            return True
    def email_invalid(self, email):
        email_regex = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if email_regex.match(email):
            return False
        else:
            return True
    def password_invalid(self, password):
        if len(password) < 8:
            return True
        else:
            return False
    def password_not_match(self, password, confirm_password):
        if password == confirm_password:
            return False
        else:
            return True
    def reg_validator(self, username, name, email, password, confirm_password):
        errors = []
        if not username:
            errors.append("Alias field must not be empty")
        if self.name_invalid(first_name):
            errors.append("Name must be more than two characters and only letters")
        if self.email_invalid(email):
            errors.append("Invalid email")
        if self.password_invalid(password):
            errors.append("Password must be 8 characters or more")
        if self.password_not_match(password, confirm_password):
            errors.append("Passwords must match")
        return errors
## returns an object with either {errors: list of errors}, or {user: user object}
    def add_user(self, username, name, email, password, confirm_password):
        errors = self.reg_validator(username, name, email, password, confirm_password)
        if errors:
            return {'errors': errors}
        else:
            try:
                hash_pw = bcrypt.hashpw(password.encode(), bcrypt.gensalt())
                user = User(username=username, name=name, email=email, hash_pw=hash_pw)
                user.save()
                return {"user": user}
            except:
                return {"errors": ["Email already registered"]}
## returns an object with either {errors: list of errors}, or {user: user object}
    def login(self, email, password):
        try:
            user = User.objects.get(email=email)
            if bcrypt.hashpw(password.encode(), user.hash_pw.encode()) == user.hash_pw:
                return {"user": user}
            else:
                return {"errors": ["Invalid email or password"]}
        except:
            return {"errors": ["Invalid email or password"]}



class User(models.Model):
    name = models.CharField(max_length=255)
    username = models.CharField(max_length=255)
    email = models.CharField(max_length=255, unique=True)
    hash_pw = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    friends = models.ManyToManyField('self', through='Friend', symmetrical=False, related_name='related_to')
    objects = UserManager()

    def __unicode__(self):
        return self.name

    def add_friend(self, person, status):
        friend, created = Friend.objects.get_or_create(
            from_person=self,
            to_person=person,
            status=status)
        return friend

    def remove_friend(self, person, status):
        Friend.objects.filter(
            from_person=self,
            to_person=person,
            status=status).delete()
        return

    def get_following(self):
        return self.get_following(FRIEND_FOLLOWING)

    def get_friends(self, status):
        return self.friends.filter(
            to_people__status=status,
            to_people__from_person=self)

    def get_related_to(self, status):
        return self.related_to.filter(
            from_people__status=status,
            from_people__to_person=self)


FRIEND_FOLLOWING = 1
FRIEND_BLOCKED = 2
FRIEND_STATUSES = (
    (FRIEND_FOLLOWING, 'Following'),
    (FRIEND_BLOCKED, 'Blocked'),
)

class Friend(models.Model):
    from_person = models.ForeignKey(User, related_name='from_people')
    to_person = models.ForeignKey(User, related_name='to_people')
    status = models.IntegerField(choices=FRIEND_STATUSES)

apps/first_app/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from models import *

def index(request):
    return render(request, 'login/index.html')

def login(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        user = User.objects.login(email, password)
        if "errors" in user:
            for error in user["errors"]:
                messages.error(request, error)
            return redirect('/')
        else:
            request.session["username"] = user["user"].username
            request.session["id"] = user["user"].id
            request.session["name"] = user["user"].name
            return redirect('main:index')
    else:
        return redirect(reverse('login/index'))

def register(request):
    if request.method == "POST":
        name = request.POST['first_name']
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        user = User.objects.add_user(name, username, email, password, confirm_password)
        if "errors" in user:
            for error in user["errors"]:
                messages.error(request, error)
            return redirect(reverse('login:index'))
        else:
            request.session["username"] = user["user"].username
            request.session["name"] = user["user"].name
            request.session["id"] = user["user"].id
            return redirect('main:index')
    else:
        return redirect(reverse('login:index'))

def logout(request):
    request.session['id'] = None
    return redirect(reverse('login:index'))

def user(request, user_id):
    if request.session['id'] == None:
		return redirect('/')
    else:
        context = {
            'user': User.objects.get(id=user_id)
            }
        return render(request, 'user.html', context)

def main(request):
    if request.session['id'] == None:
		return redirect('/')
    user = User.objects.get(id = request.session['id'])
    friends = user.friends.all()
    friendlist = []
    for f in friends:
        friendlist.append(f)
    notfriends = User.objects.all().exclude(name=user.name)
    for x in friendlist:
        notfriends = notfriends.exclude(name=x.name)
    context = {
        'user':request.session['id'],
        'friends': friends,
        'notfriends': notfriends,
    }
    return render(request, 'home.html', context)

def newfriend(request, user_id):
    current_user = User.objects.get(id= request.session['id'])
    newfriend = User.objects.get(id=user_id)
    current_user.add_friend(newfriend, FRIEND_FOLLOWING)
    return redirect('/main')

def byefriend(request, user_id):
    current_user = User.objects.get(id= request.session['id'])
    oldfriend = User.objects.get(id=user_id)
    current_user.remove_friend(oldfriend, FRIEND_FOLLOWING)
    return redirect('/main')

apps/first_app/templates/home.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
    {% load staticfiles %}
        <link rel="stylesheet" href="{% static '../static/styles.css' %}" />
        <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
  </head>
  <body>



    <div class="container">
      <div class="navbar navbar-light bg-faded">
        <span class="navbar-text">
          {% if messages %}
            <ul class="messages">
            {% for message in messages %}
              <li {% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</li>
            {% endfor %}
            </ul>
          {% endif %}
        </span>
        <a href="{% url 'main:logout'%}" style="float:right">Logout</a>
      </div>
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-8">
          <h2>Hello, {{request.session.name}}!</h2><br /><br />
          <h4><u>Here is the list of your friends:</u></h4><br />
          {% if friends %}
          <table class="table table-striped">

            <thead style="background-color: #4CAF50;color: white;">
              <tr>
                <th>Alias</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody>

              {% for f in friends %}
              <tr>
                <td>{{ f.name }}</td>
                <td><a href="/user/{{ f.id }}" class="btn btn-primary">View Profile</a>    <a href="/deletefriend/{{ f.id }}" class="btn btn-danger">Delete Friend</a></td>

              </tr>
              {% endfor %}
            </tbody>
          </table>
            {% else %}
            <div class="alert alert-warning" role="alert">
            <h3>Uh Oh! You don't have any friends yet.</h3>
          </div>
          {% endif %}
        </div>
      </div>
      <div class="row"></div>
      <div class="row"></div>
      <div class="row"></div>
      <hr />
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-8">
        <h4><u>Other Users not on your friend's list:</u></h4>
        <table class="table table-striped">
        {% if notfriends %}
          <thead style="background-color: #4CAF50;color: white;">
            <tr>
              <th>Alias</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
            {% for user in notfriends %}
            <tr>
              <td><a href="/user/{{ user.id }}">{{ user.name }}</a></td>
              <td><a href="/addfriend/{{user.id}}" class="btn btn-info">Add Friend</a></td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% endif %}
        </div>
      </div>
    </div>
  </body>
</html>

apps/first_app/templates/login/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Login Page</title>
    {% load staticfiles %}
        <link rel="stylesheet" href="{% static '../static/styles.css' %}" />
        <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
  </head>
  <body>

      {% if messages %}
      <div class="container">
        <div class="row">
          <div class="col-md-12">
          <div class="alert alert-danger">
          <ul class="messages">
          {% for message in messages %}
            <li {% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</li>
          {% endfor %}
          </ul>
        </div>
        </div>
        </div>
        </div>
      {% endif %}

    <div class="container">
      <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-4">
          <div id="register">
            <h1>Register:</h1>
            <hr />
            <form action="{% url 'login:register'%}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                <label for="first_name">Name: </label>
                <input type="text" class="form-control" name="first_name"><br />
              </div>
              <div class="form-group">
                <label for="username">Alias: </label>
                <input type="text" class="form-control" name="username"><br />
              </div>
              <div class="form-group">
                <label for="email">Email: </label>
                <input type="text" class="form-control" name="email"><br />
              </div>
              <div class="form-group">
                <label for="password">Password: </label>
                <input type="password" class="form-control" name="password"><br />
              </div>
              <div class="form-group">
                <label for="confirm_password">Confirm PW: </label>
                <input type="password" class="form-control" name="confirm_password"><br />
              </div>
              <input type="submit" value="Register">
            </form>
          </div>
        </div>
        <div class="col-md-2"></div>
        <div class="col-md-4">
            <h1>Log in:</h1>
            <hr />
            <form action="{% url 'login:login'%}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                <label for="email">Email: </label>
                <input type="text" class="form-control" name="email"><br />
              </div>
              <div class="form-group">
                <label for="password">Password: </label>
                <input type="password" class="form-control" name="password"><br />
              </div>
              <input type="submit" value="Log in">
            </form>
        </div>
      </div>
    </div>
  </body>
</html>

apps/first_app/templates/user.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Home</title>
    {% load staticfiles %}
        <link rel="stylesheet" href="{% static '../static/styles.css' %}" />
        <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap.min.css">
        <link rel="stylesheet" href="/static/bootstrap/dist/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <div class="navbar navbar-light bg-faded">
        <span class="navbar-text">
          {% if messages %}
            <ul class="messages">
            {% for message in messages %}
              <li {% if message.tags %} class="{{message.tags}}"{% endif %}>{{message}}</li>
            {% endfor %}
            </ul>
          {% endif %}
        </span>
        <div class="navlinks" style="float:right">
          <a href="{% url 'main:main'%}">Home |</a>
          <a href="{% url 'main:logout'%}">Logout</a>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-8">
          <h2>{{ user.name }}'s Profile</h2><hr />
          <h4>Name: {{ user.name }}</h4>
          <h4>Email Address: {{ user.email }}</h4>
        </div>
      </div>
  </body>
  </html>